# Generated by Django 4.2.2 on 2023-07-03 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FOUNDATION', 'fundacja'), ('NON-GOVERNMENTAL ORGANIZATION', 'organizacja pozarządowa'), ('LOCAL_COLLECTION', 'zbiórka lokalna')], default='FOUNDATION', max_length=125)),
                ('categories', models.ManyToManyField(to='Oddam_w_dobre_ręce_App.category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=125)),
                ('phone_number', models.CharField(max_length=9)),
                ('city', models.CharField(max_length=125)),
                ('zip_code', models.CharField(max_length=6)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='Oddam_w_dobre_ręce_App.category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oddam_w_dobre_ręce_App.institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
